/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AreaBox: typeof import('./src/components/AreaBox.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LineArea: typeof import('./src/components/LineArea.vue')['default']
    NumBox: typeof import('./src/components/NumBox.vue')['default']
    PieBox: typeof import('./src/components/PieBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwitch: typeof import('vant/es')['Switch']
  }
}
